# Build phase
FROM node:23-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
# CMD [ "npm", "run", "test" ]

# Run phase
FROM nginx
COPY --from=builder /app/dist /usr/share/nginx/html
